export type Screen = "home" | "levels" | "achievements" | "character";

export const HERO_COLORS = ["#FF6B2B", "#00BFEA", "#2ECC71", "#A855F7", "#FF6EB4", "#FFD700"];
export const HERO_HATS = ["🎩", "⛑️", "👒", "🪖", "🎓", "👑"];
export const HERO_ACCESSORIES = ["🚒", "🏥", "🛡️", "⚡", "🔦", "🧰"];
export const HERO_NAMES = ["Алёша", "Маша", "Витя", "Соня", "Дима", "Катя"];

export const LEVELS = [
  {
    id: 1,
    title: "Пожарная безопасность",
    emoji: "🔥",
    desc: "Научись спасаться при пожаре",
    color: "#FF6B2B",
    border: "#CC4400",
    bg: "from-orange-100 to-red-100",
    difficulty: "Лёгкий",
    diffColor: "bg-green-100 text-green-700",
    stars: 3,
    locked: false,
    xp: 150,
  },
  {
    id: 2,
    title: "Потерялся в городе",
    emoji: "🏙️",
    desc: "Найди путь домой в большом городе",
    color: "#00BFEA",
    border: "#006699",
    bg: "from-blue-100 to-cyan-100",
    difficulty: "Лёгкий",
    diffColor: "bg-green-100 text-green-700",
    stars: 2,
    locked: false,
    xp: 120,
  },
  {
    id: 3,
    title: "Незнакомцы",
    emoji: "👤",
    desc: "Как вести себя с незнакомыми людьми",
    color: "#A855F7",
    border: "#5B21B6",
    bg: "from-purple-100 to-pink-100",
    difficulty: "Средний",
    diffColor: "bg-yellow-100 text-yellow-700",
    stars: 1,
    locked: false,
    xp: 200,
  },
  {
    id: 4,
    title: "Первая помощь",
    emoji: "🏥",
    desc: "Как помочь пострадавшему",
    color: "#2ECC71",
    border: "#1A8A45",
    bg: "from-green-100 to-teal-100",
    difficulty: "Средний",
    diffColor: "bg-yellow-100 text-yellow-700",
    stars: 0,
    locked: false,
    xp: 250,
  },
  {
    id: 5,
    title: "Природные катастрофы",
    emoji: "⛈️",
    desc: "Действия при стихийных бедствиях",
    color: "#FF4757",
    border: "#CC0011",
    bg: "from-red-100 to-orange-100",
    difficulty: "Сложный",
    diffColor: "bg-red-100 text-red-700",
    stars: 0,
    locked: true,
    xp: 350,
  },
  {
    id: 6,
    title: "Кибербезопасность",
    emoji: "💻",
    desc: "Безопасность в интернете",
    color: "#FFD700",
    border: "#CC8800",
    bg: "from-yellow-100 to-amber-100",
    difficulty: "Сложный",
    diffColor: "bg-red-100 text-red-700",
    stars: 0,
    locked: true,
    xp: 400,
  },
];

export const ACHIEVEMENTS = [
  { id: 1, title: "Первые шаги", desc: "Завершил первый уровень", emoji: "👣", unlocked: true, color: "#FF6B2B" },
  { id: 2, title: "Герой огня", desc: "Прошёл уровень с пожаром на 3 звезды", emoji: "🔥", unlocked: true, color: "#FF6B2B" },
  { id: 3, title: "Навигатор", desc: "Помог герою найти дорогу домой", emoji: "🧭", unlocked: true, color: "#00BFEA" },
  { id: 4, title: "Осторожный", desc: "Правильно отреагировал на незнакомца", emoji: "🛡️", unlocked: true, color: "#A855F7" },
  { id: 5, title: "Доктор Знаний", desc: "Изучи первую помощь", emoji: "🏥", unlocked: false, color: "#2ECC71" },
  { id: 6, title: "Коллектор звёзд", desc: "Собери 10 звёзд", emoji: "⭐", unlocked: false, color: "#FFD700" },
  { id: 7, title: "Суперспасатель", desc: "Пройди все уровни", emoji: "🦸", unlocked: false, color: "#FF4757" },
  { id: 8, title: "Кибергерой", desc: "Мастер безопасности в сети", emoji: "💻", unlocked: false, color: "#A855F7" },
];
